#!/bin/bash

./script g$1 > in$1.txt
./script s < in$1.txt > out$1.txt
./script s_log < in$1.txt > out$1_naive.txt

g++ -O2 -std=c++17 -Wall -Wextra -Wconversion check.cpp
./a.out in$1.txt out$1.txt out$1_naive.txt

rm out$1.txt 
rm out$1_naive.txt
rm a.out