#!/bin/bash

./validate $1
./script s in$1 out$1
python3 s.py < in$1.txt > out$1_py.txt

g++ -O2 -std=c++17 -Wall -Wextra -Wconversion check.cpp
./a.out in$1.txt out$1.txt out$1_py.txt

rm out$1.txt 
rm out$1_py.txt
rm a.out